### PR TITLE
Two new features added.

### PR DESCRIPTION
**Pull request by altsoph**
Two new features added: the palette enforcement and the smoothness enforcement.
I added several options to "vq_parser" and made minor changes in ascend_txt() (added two new losses).
Plus, a new demo notebook included.

### CODE REVIEW

**Comment by dribnet** [comment]
Thanks, this looks very promising! I have a slightly different approach brewing in #2, but it appears that these approaches are mostly complimentary so my plan is to leave both versions in initially.

The only thing I'd like to standardise is the palette specification itself. I'm happy with the `target_palette` setting for this, but have simplified it to be a string which currently supports either the "custom" format from your notebook (list of #hex1,#hex2,...) or a string like "red" or "orange" for a predefined linear 16 color table. You can find this change in my `enforce_palette_annealing` branch.

I'll update again after I add some ideas for specifying a palette from a string.

**Comment by dribnet** [comment]
Hi - I've merged in my changes and so let me know if you have any further improvements and then I'm happy to roll a release with this new capability.

**Comment by dribnet** [comment]
Relatedly - I've noticed that `--enforce_smoothness=50` provides an interesting result, but also invariably makes the image darker, so we might want to do some testing with that setting to make sure there isn't a bias toward black.

**Comment by altsoph** [comment]
> Relatedly - I've noticed that `--enforce_smoothness=50` provides an interesting result, but also invariably makes the image darker, so we might want to do some testing with that setting to make sure there isn't a bias toward black.

Indeed! To be precise, it isn't a bias toward black; it's rather a bias toward low saturation, I'd say.
This is one of the issues I targeted in my new patch, and I have some promising results.
Gonna describe it and merge it no longer than the end of this weekend :)

**Comment by z3Nsk1Fh5a** [comment]
As a noob enjoying the colabs, just tried the notebook and I am getting this 



`Using device: cuda:0
Optimising using: AdamP
Using text prompts: ['A man fishing in a stream, a bear watches the man from the other side of the stream. #pixelart']
Using seed: 12665054336841403298
0/? [00:01<?, ?it/s]
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:3613: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
/usr/local/lib/python3.7/dist-packages/kornia/geometry/transform/imgwarp.py:99: UserWarning: The align_corners default value has been changed. By default now is set True in order to match cv2.warpPerspective. In case you want to keep your previous behaviour set it to False. This warning will disappear in kornia > v0.6.
  warnings.warn(message)`
---------------------------------------------------------------------------
`TypeError                                 Traceback (most recent call last)
<ipython-input-10-b640d0e40a4d> in <module>()
     82 settings = clipit.apply_settings()
     83 clipit.do_init(settings)
---> 84 clipit.do_run(settings)

2 frames
/content/clipit/clipit.py in ascend_txt(args)
    760         diffs = _pixels - target_palette[best_guesses]
    761         palette_loss = torch.mean( torch.norm( diffs, 2, dim=1 ) )*cur_cutouts[cutoutSize].shape[0]
--> 762         result.append( palette_loss*cur_iteration/args.enforce_palette_annealing )
    763 
    764     if args.enforce_smoothness:

TypeError: unsupported operand type(s) for /: 'Tensor' and 'str'
`

**Pull request merged**
